name: Lint YAML Files

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint
        run: yamllint .
